changelog:
  exclude:
    labels:
      - ci/cd
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: New Additions
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
